/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu_input;

import Connection.connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Form_user.Form_login;
import Menu.Menu_Admin;
import Transaksi.Form_peminjaman;
import Transaksi.Form_pengembalian;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Form_mahasiswa extends javax.swing.JFrame {
    public Connection con;
    public PreparedStatement pst;
    
    public Form_mahasiswa() {

        initComponents();
        this.setLocationRelativeTo(null);
        tampil_Table_mahasiswa();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroud = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data_buku = new javax.swing.JLabel();
        peminjaman = new javax.swing.JLabel();
        pengembaian = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        text_fakultas = new javax.swing.JTextField();
        label_fakultas = new javax.swing.JLabel();
        text_ta = new javax.swing.JTextField();
        label_no_telp = new javax.swing.JLabel();
        text_prodi = new javax.swing.JTextField();
        label_prodi = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        label_nama = new javax.swing.JLabel();
        label_jenis_kelamin = new javax.swing.JLabel();
        text_nim = new javax.swing.JTextField();
        label_nim = new javax.swing.JLabel();
        text_no_telp = new javax.swing.JTextField();
        label_ta = new javax.swing.JLabel();
        text_alamat = new javax.swing.JTextField();
        label_alamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_mahasiswa = new javax.swing.JTable();
        combo_jenis_kelamin = new javax.swing.JComboBox<>();
        text_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Backgroud.setBackground(new java.awt.Color(27, 188, 155));
        Backgroud.setForeground(new java.awt.Color(27, 188, 155));
        Backgroud.setPreferredSize(new java.awt.Dimension(902, 475));

        Header.setBackground(new java.awt.Color(1, 50, 67));
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(27, 188, 155));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Menu Admin");

        beranda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        beranda.setText("Beranda");
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Digital");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Satya Wacana Christian University");

        jLabel3.setBackground(new java.awt.Color(27, 188, 155));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 188, 155));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Library");

        data_buku.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        data_buku.setForeground(new java.awt.Color(255, 255, 255));
        data_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        data_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Book Kecil.png"))); // NOI18N
        data_buku.setText("Data Buku");
        data_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_bukuMouseClicked(evt);
            }
        });

        peminjaman.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Borrow.png"))); // NOI18N
        peminjaman.setText("Peminjaman");
        peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanMouseClicked(evt);
            }
        });

        pengembaian.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pengembaian.setForeground(new java.awt.Color(255, 255, 255));
        pengembaian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pengembaian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        pengembaian.setText("Pengembalian");
        pengembaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembaianMouseClicked(evt);
            }
        });

        laporan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Report Kecil.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(beranda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_buku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pengembaian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laporan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengembaian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)))
        );

        text_fakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_fakultasActionPerformed(evt);
            }
        });

        label_fakultas.setBackground(new java.awt.Color(255, 255, 255));
        label_fakultas.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_fakultas.setForeground(new java.awt.Color(255, 255, 255));
        label_fakultas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_fakultas.setText("Fakultas");

        text_ta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_taActionPerformed(evt);
            }
        });

        label_no_telp.setBackground(new java.awt.Color(255, 255, 255));
        label_no_telp.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_no_telp.setForeground(new java.awt.Color(255, 255, 255));
        label_no_telp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_no_telp.setText("No.Telpon");

        text_prodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_prodiActionPerformed(evt);
            }
        });

        label_prodi.setBackground(new java.awt.Color(255, 255, 255));
        label_prodi.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_prodi.setForeground(new java.awt.Color(255, 255, 255));
        label_prodi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_prodi.setText("Program Studi");

        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });

        label_nama.setBackground(new java.awt.Color(255, 255, 255));
        label_nama.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_nama.setForeground(new java.awt.Color(255, 255, 255));
        label_nama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nama.setText("Nama");

        label_jenis_kelamin.setBackground(new java.awt.Color(255, 255, 255));
        label_jenis_kelamin.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_jenis_kelamin.setForeground(new java.awt.Color(255, 255, 255));
        label_jenis_kelamin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_jenis_kelamin.setText("Jenis Kelamin");

        text_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nimActionPerformed(evt);
            }
        });

        label_nim.setBackground(new java.awt.Color(255, 255, 255));
        label_nim.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_nim.setForeground(new java.awt.Color(255, 255, 255));
        label_nim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim.setText("Nim");

        text_no_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_no_telpActionPerformed(evt);
            }
        });

        label_ta.setBackground(new java.awt.Color(255, 255, 255));
        label_ta.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_ta.setForeground(new java.awt.Color(255, 255, 255));
        label_ta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_ta.setText("Tahun Angkatan");

        text_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamatActionPerformed(evt);
            }
        });

        label_alamat.setBackground(new java.awt.Color(255, 255, 255));
        label_alamat.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_alamat.setForeground(new java.awt.Color(255, 255, 255));
        label_alamat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_alamat.setText("Alamat");

        Table_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", null, null, "", null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Fakultas", "Program Studi", "Tahun Angkatan", "Jenis Kelamin", "Alamat", "No. Telpon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_mahasiswa);

        combo_jenis_kelamin.setEditable(true);
        combo_jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        text_search.setBackground(new java.awt.Color(27, 188, 155));
        text_search.setForeground(new java.awt.Color(255, 255, 255));
        text_search.setBorder(null);
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon Search.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(101, 198, 187));
        btn_save.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(1, 50, 67));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.setActionCommand("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(101, 198, 187));
        btn_delete.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(1, 50, 67));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btn_delete.setText("delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(101, 198, 187));
        btn_edit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(1, 50, 67));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(101, 198, 187));
        btn_reset.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(1, 50, 67));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroudLayout = new javax.swing.GroupLayout(Backgroud);
        Backgroud.setLayout(BackgroudLayout);
        BackgroudLayout.setHorizontalGroup(
            BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addComponent(label_nim)
                                .addGap(104, 104, 104))
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addComponent(text_nim)
                                .addGap(22, 22, 22)))
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama)
                            .addComponent(text_nama)))
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addComponent(text_fakultas)
                        .addGap(22, 22, 22)
                        .addComponent(text_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text_ta)
                            .addComponent(label_fakultas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_ta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_jenis_kelamin, 0, 104, Short.MAX_VALUE)
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_jenis_kelamin)
                                    .addComponent(label_prodi))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_alamat)
                            .addComponent(text_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(label_no_telp))
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(text_no_telp)))))
                .addGap(21, 21, 21)
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_search)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search)
                        .addGap(20, 20, 20))))
        );
        BackgroudLayout.setVerticalGroup(
            BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroudLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(BackgroudLayout.createSequentialGroup()
                            .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroudLayout.createSequentialGroup()
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_ta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_ta)
                            .addComponent(combo_jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_delete)
                    .addComponent(btn_edit)
                    .addComponent(btn_reset))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        Menu_Admin rgs = new Menu_Admin();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_berandaMouseClicked

    private void data_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_bukuMouseClicked
        Form_buku rgs = new Form_buku();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_data_bukuMouseClicked

    private void peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMouseClicked
        Form_peminjaman rgs = new Form_peminjaman();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_peminjamanMouseClicked

    private void pengembaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembaianMouseClicked
        Form_pengembalian rgs = new Form_pengembalian();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pengembaianMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        JOptionPane.showMessageDialog(null,"Hello");
    }//GEN-LAST:event_laporanMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        Form_login rgs = new Form_login();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_keluarMouseClicked

    private void text_taActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_taActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_taActionPerformed

    private void text_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamatActionPerformed

    private void text_prodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_prodiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_prodiActionPerformed

    private void text_no_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_no_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_no_telpActionPerformed

    private void text_fakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_fakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_fakultasActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nimActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String nim="", nama="", fakultas="", program_studi="", tahun_angkatan="", jenis_kelamin="", alamat="", no_telp="";
        
        nim = text_nim.getText();
        nama = text_nama.getText();
        fakultas = text_fakultas.getText();
        program_studi = text_prodi.getText();
        tahun_angkatan = text_ta.getText();
        jenis_kelamin = (String) combo_jenis_kelamin.getSelectedItem();
        alamat = text_alamat.getText();
        no_telp = text_no_telp.getText();
       
        con = connection.getConnection();
        try {
            
            String sql = "insert into tb_mahasiswa values (?,?,?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) 
            con.prepareStatement(sql);
            
            stat.setString(1, nim);
            stat.setString(2, nama);
            stat.setString(3, fakultas);
            stat.setString(4, program_studi);
            stat.setString(5, tahun_angkatan);
            stat.setString(6, jenis_kelamin);
            stat.setString(7, alamat);
            stat.setString(8, no_telp);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL","Informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
            tampil_Table_mahasiswa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        con = connection.getConnection();
        String nim="", nama="", fakultas="", program_studi="", tahun_angkatan="", jenis_kelamin="", alamat="", no_telp="";
        
        nim = text_nim.getText();
        nama = text_nama.getText();
        fakultas = text_fakultas.getText();
        program_studi = text_prodi.getText();
        tahun_angkatan = text_ta.getText();
        jenis_kelamin = (String) combo_jenis_kelamin.getSelectedItem();
        alamat = text_alamat.getText();
        no_telp = text_no_telp.getText();
        
        if (tahun_angkatan==null){
            JOptionPane.showMessageDialog(null, "Silahkan isi tahun angkatan","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            String sql="update tb_mahasiswa set nama=?, fakultas=?, program_studi=?, tahun_angkatan=?, jenis_kelamin=?, alamat=?, no_telp=? where nim='"+nim+"'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, fakultas);
                stat.setString(3, program_studi);
                stat.setString(4, tahun_angkatan);
                stat.setString(5, jenis_kelamin);
                stat.setString(6, alamat);
                stat.setString(7, no_telp);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data BERHASIL di Ubah");
                tampil_Table_mahasiswa();
                reset();
            }catch(SQLException se){
                JOptionPane.showMessageDialog(null,"Data GAGAL di Ubah");
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void Table_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_mahasiswaMouseClicked
        kliktable();
    }//GEN-LAST:event_Table_mahasiswaMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int baris = Table_mahasiswa.getSelectedRow();
        String nim = tabmode.getValueAt(baris, 0).toString();        
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda yakin ingin menghapus data Mahasiswa Nim : "+nim+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                con = connection.getConnection();
                String sql="delete from tb_mahasiswa where nim='"+nim+"'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Data Berhasil di hapus");
                tampil_Table_mahasiswa();
                reset();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        pencarian_mahasiswa();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
        pencarian_mahasiswa();
    }//GEN-LAST:event_text_searchActionPerformed
    public void pencarian_mahasiswa(){
        String cari = text_search.getText();
        
       Object[] Baris={"nim","nama","fakultas","program_studi","tahun_angkatan","jenis_kelamin","alamat","no_telp"};
       tabmode = new DefaultTableModel(null, Baris);
       Table_mahasiswa.setModel(tabmode);

       con = connection.getConnection();
       
       try{
           String sql="Select * from tb_mahasiswa where "
                   + "nim like '%"+cari+"%' "
                   + "OR nama like '%"+cari+"%' "
                   + "OR fakultas like '%"+cari+"%' "
                   + "OR program_studi like '%"+cari+"%' "
                   + "OR tahun_angkatan like '%"+cari+"%' "
                   + "OR jenis_kelamin like '%"+cari+"%' "
                   + "OR alamat like '%"+cari+"%' "
                   + "OR no_telp like '%"+cari+"%' "
                   + "order by nim asc";
           java.sql.Statement stmt=con.createStatement();
           java.sql.ResultSet rslt=stmt.executeQuery(sql);
           while(rslt.next()){
               String nim=rslt.getString("nim");
               String nama=rslt.getString("nama");
               String fakultas=rslt.getString("fakultas");
               String program_studi=rslt.getString("program_studi");
               String tahun_angkatan=rslt.getString("tahun_angkatan");
               String jenis_kelamin=rslt.getString("jenis_kelamin");
               String alamat=rslt.getString("alamat");
               String no_telp=rslt.getString("no_telp");
               
               String[] dataField={nim,nama,fakultas,program_studi,tahun_angkatan,jenis_kelamin,alamat,no_telp};
               tabmode.addRow(dataField);
           }
       }
       catch(Exception ex){
       }
    }
    
    public void reset(){
        text_nim.setText("");
        text_nama.setText("");
        text_fakultas.setText("");
        text_prodi.setText("");
        text_ta.setText("");
        text_alamat.setText("");
        text_no_telp.setText("");
    }
    private void kliktable(){
        int baris = Table_mahasiswa.getSelectedRow();
        text_nim.setText((String)Table_mahasiswa.getValueAt(baris, 0));
        text_nama.setText((String)Table_mahasiswa.getValueAt(baris, 1));
        text_fakultas.setText((String)Table_mahasiswa.getValueAt(baris, 2));
        text_prodi.setText((String)Table_mahasiswa.getValueAt(baris, 3));
        text_ta.setText((String)Table_mahasiswa.getValueAt(baris, 4));
        //combo_jenis_kelamin.getSelectedItem((String)Table_mahasiswa.getValueAt(baris, 5));
        text_alamat.setText((String)Table_mahasiswa.getValueAt(baris, 6));
        text_no_telp.setText((String)Table_mahasiswa.getValueAt(baris, 7));
    }
    
    private DefaultTableModel tabmode;
        public void tampil_Table_mahasiswa(){
        Object []baris = {"nim","Nama","fakultas","program_studi","tahun_angkatan","jenis_kelamin","alamat","no_telp"};
        tabmode = new DefaultTableModel(null, baris);
        Table_mahasiswa.setModel(tabmode);
        con = connection.getConnection();
        try {
            String sql = "select * from tb_mahasiswa order by nim asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String nim = hasil.getString("nim");
                String nama = hasil.getString("nama");
                String fakultas = hasil.getString("fakultas");
                String program_studi = hasil.getString("program_studi");
                String tahun_angkatan = hasil.getString("tahun_angkatan"); 
                String jenis_kelamin = hasil.getString("jenis_kelamin");
                String alamat = hasil.getString("alamat"); 
                String no_telp = hasil.getString("no_telp");
                String[] data = {nim, nama, fakultas, program_studi, tahun_angkatan, jenis_kelamin, alamat, no_telp};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL","Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroud;
    private javax.swing.JPanel Header;
    private javax.swing.JTable Table_mahasiswa;
    private javax.swing.JLabel beranda;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel btn_search;
    private javax.swing.JComboBox<String> combo_jenis_kelamin;
    private javax.swing.JLabel data_buku;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_fakultas;
    private javax.swing.JLabel label_jenis_kelamin;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_no_telp;
    private javax.swing.JLabel label_prodi;
    private javax.swing.JLabel label_ta;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel peminjaman;
    private javax.swing.JLabel pengembaian;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JTextField text_fakultas;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nim;
    private javax.swing.JTextField text_no_telp;
    private javax.swing.JTextField text_prodi;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_ta;
    // End of variables declaration//GEN-END:variables
}
