/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Connection.connection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import Form_user.Form_login;
import Menu.Menu_Admin;
import Menu_input.Form_buku;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Form_pengembalian extends javax.swing.JFrame {

    public Connection con;
    public PreparedStatement pst;
    
    public Form_pengembalian() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampil_Table_pengembalian();
        tampil_Table_peminjaman();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backgroud = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        beranda = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        data_buku = new javax.swing.JLabel();
        peminjaman = new javax.swing.JLabel();
        pengembaian = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_peminjaman = new javax.swing.JTable();
        text_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        label_nim = new javax.swing.JLabel();
        text_nim = new javax.swing.JTextField();
        text_tanggal_pinjam = new javax.swing.JTextField();
        label_judul_buku = new javax.swing.JLabel();
        text_tanggal_kembali = new javax.swing.JTextField();
        label_pengarang = new javax.swing.JLabel();
        text_keterlambatan = new javax.swing.JTextField();
        label_tanggal_pinjam = new javax.swing.JLabel();
        text_denda = new javax.swing.JTextField();
        label_tanggal_pinjam1 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        label_nama = new javax.swing.JLabel();
        label_program_studi = new javax.swing.JLabel();
        text_program_studi = new javax.swing.JTextField();
        text_kode_buku = new javax.swing.JTextField();
        label_kode_buku = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_pengembalian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Backgroud.setBackground(new java.awt.Color(27, 188, 155));
        Backgroud.setForeground(new java.awt.Color(27, 188, 155));
        Backgroud.setPreferredSize(new java.awt.Dimension(902, 475));

        Header.setBackground(new java.awt.Color(1, 50, 67));
        Header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(27, 188, 155));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Menu Admin");

        beranda.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        beranda.setForeground(new java.awt.Color(255, 255, 255));
        beranda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home.png"))); // NOI18N
        beranda.setText("Beranda");
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Digital");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Satya Wacana Christian University");

        jLabel3.setBackground(new java.awt.Color(27, 188, 155));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(27, 188, 155));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Library");

        data_buku.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        data_buku.setForeground(new java.awt.Color(255, 255, 255));
        data_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        data_buku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Book Kecil.png"))); // NOI18N
        data_buku.setText("Data Buku");
        data_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_bukuMouseClicked(evt);
            }
        });

        peminjaman.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        peminjaman.setForeground(new java.awt.Color(255, 255, 255));
        peminjaman.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Borrow.png"))); // NOI18N
        peminjaman.setText("Peminjaman");
        peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanMouseClicked(evt);
            }
        });

        pengembaian.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pengembaian.setForeground(new java.awt.Color(255, 255, 255));
        pengembaian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pengembaian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        pengembaian.setText("Pengembalian");
        pengembaian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembaianMouseClicked(evt);
            }
        });

        laporan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Report Kecil.png"))); // NOI18N
        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });

        keluar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        keluar.setForeground(new java.awt.Color(255, 255, 255));
        keluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(beranda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data_buku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peminjaman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pengembaian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laporan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)))
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pengembaian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)))
        );

        Table_peminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", "", null, null, ""},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Program Studi", "Kode Buku", "Judul Buku", "Pengarang", "Tanggal Pinjam"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_peminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_peminjaman);

        text_search.setBackground(new java.awt.Color(27, 188, 155));
        text_search.setForeground(new java.awt.Color(255, 255, 255));
        text_search.setText("Search Pengembalian");
        text_search.setBorder(null);
        text_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_searchMouseClicked(evt);
            }
        });
        text_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_searchActionPerformed(evt);
            }
        });

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon Search.png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(101, 198, 187));
        btn_save.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btn_save.setForeground(new java.awt.Color(1, 50, 67));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.setActionCommand("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(101, 198, 187));
        btn_delete.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(1, 50, 67));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(101, 198, 187));
        btn_edit.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(1, 50, 67));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(101, 198, 187));
        btn_reset.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(1, 50, 67));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(1, 50, 67));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(27, 188, 155));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pengembalian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 0, 18), new java.awt.Color(1, 50, 67))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(1, 50, 67));

        label_nim.setBackground(new java.awt.Color(255, 255, 255));
        label_nim.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_nim.setForeground(new java.awt.Color(255, 255, 255));
        label_nim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nim.setText("Nim");

        text_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nimActionPerformed(evt);
            }
        });

        text_tanggal_pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tanggal_pinjamActionPerformed(evt);
            }
        });

        label_judul_buku.setBackground(new java.awt.Color(255, 255, 255));
        label_judul_buku.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_judul_buku.setForeground(new java.awt.Color(255, 255, 255));
        label_judul_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_judul_buku.setText("Tanggal Pinjam");

        text_tanggal_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tanggal_kembaliActionPerformed(evt);
            }
        });

        label_pengarang.setBackground(new java.awt.Color(255, 255, 255));
        label_pengarang.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_pengarang.setForeground(new java.awt.Color(255, 255, 255));
        label_pengarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_pengarang.setText("Tanggal Kembali");

        text_keterlambatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_keterlambatanActionPerformed(evt);
            }
        });

        label_tanggal_pinjam.setBackground(new java.awt.Color(255, 255, 255));
        label_tanggal_pinjam.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_tanggal_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        label_tanggal_pinjam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_tanggal_pinjam.setText("Keterlambatan");

        text_denda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_dendaActionPerformed(evt);
            }
        });

        label_tanggal_pinjam1.setBackground(new java.awt.Color(255, 255, 255));
        label_tanggal_pinjam1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_tanggal_pinjam1.setForeground(new java.awt.Color(255, 255, 255));
        label_tanggal_pinjam1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_tanggal_pinjam1.setText("Denda");

        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });

        label_nama.setBackground(new java.awt.Color(255, 255, 255));
        label_nama.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_nama.setForeground(new java.awt.Color(255, 255, 255));
        label_nama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_nama.setText("Nama");

        label_program_studi.setBackground(new java.awt.Color(255, 255, 255));
        label_program_studi.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_program_studi.setForeground(new java.awt.Color(255, 255, 255));
        label_program_studi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_program_studi.setText("Program Studi");

        text_program_studi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_program_studiActionPerformed(evt);
            }
        });

        text_kode_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_kode_bukuActionPerformed(evt);
            }
        });

        label_kode_buku.setBackground(new java.awt.Color(255, 255, 255));
        label_kode_buku.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        label_kode_buku.setForeground(new java.awt.Color(255, 255, 255));
        label_kode_buku.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_kode_buku.setText("Kode Buku");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(label_tanggal_pinjam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_keterlambatan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_pengarang)
                            .addComponent(label_judul_buku)
                            .addComponent(label_nim)
                            .addComponent(label_nama)
                            .addComponent(label_program_studi)
                            .addComponent(label_kode_buku))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_tanggal_pinjam, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_tanggal_kembali, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_program_studi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(label_tanggal_pinjam1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_denda, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_program_studi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_program_studi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_kode_buku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_judul_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tanggal_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tanggal_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tanggal_pinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_keterlambatan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_denda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tanggal_pinjam1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Tabel Peminjaman");

        Table_pengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null, null, "", null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Program Studi", "Kode Buku", "Tanggal Pinjam", "Tanggal Kembali", "Keterlambatan", "Denda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table_pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_pengembalianMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Table_pengembalian);

        javax.swing.GroupLayout BackgroudLayout = new javax.swing.GroupLayout(Backgroud);
        Backgroud.setLayout(BackgroudLayout);
        BackgroudLayout.setHorizontalGroup(
            BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroudLayout.createSequentialGroup()
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addGap(675, 675, 675)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_search)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search))
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroudLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(244, 244, 244))
                            .addGroup(BackgroudLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroudLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroudLayout.createSequentialGroup()
                                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane4))))))
                .addContainerGap())
        );
        BackgroudLayout.setVerticalGroup(
            BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroudLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroudLayout.createSequentialGroup()
                        .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroudLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(BackgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_save)
                            .addComponent(btn_delete)
                            .addComponent(btn_edit)
                            .addComponent(btn_reset)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        Menu_Admin rgs = new Menu_Admin();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_berandaMouseClicked

    private void data_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_bukuMouseClicked
        Form_buku rgs = new Form_buku();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_data_bukuMouseClicked

    private void peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanMouseClicked
        Form_peminjaman rgs = new Form_peminjaman();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_peminjamanMouseClicked

    private void pengembaianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembaianMouseClicked
        Form_pengembalian rgs = new Form_pengembalian();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_pengembaianMouseClicked

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        JOptionPane.showMessageDialog(null, "Belom ada");
    }//GEN-LAST:event_laporanMouseClicked

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        Form_login rgs = new Form_login();
        rgs.setVisible(true);
        rgs.pack();
        rgs.setLocationRelativeTo(null);
        rgs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_keluarMouseClicked

    private void Table_peminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_peminjamanMouseClicked

    }//GEN-LAST:event_Table_peminjamanMouseClicked

    private void text_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_searchActionPerformed
        pencarian_pengembalian();
    }//GEN-LAST:event_text_searchActionPerformed

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        pencarian_pengembalian();
    }//GEN-LAST:event_btn_searchMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String nim = "", nama = "", program_studi = "", kode_buku = "", tanggal_pinjam, tanggal_kembali, keterlambatan="",denda="";

        nim = text_nim.getText();
        nama = text_nama.getText();
        program_studi = text_program_studi.getText();
        kode_buku = text_kode_buku.getText();
        tanggal_pinjam = text_tanggal_pinjam.getText();
        tanggal_kembali = text_tanggal_kembali.getText();
        keterlambatan = text_keterlambatan.getText();
        denda = text_denda.getText();

        con = connection.getConnection();
        try {

            String sql = "insert into tb_pengembalian values (?,?,?,?,?,?,?,?)";
            PreparedStatement stat = (PreparedStatement) con.prepareStatement(sql);

            stat.setString(1, nim);
            stat.setString(2, nama);
            stat.setString(3, program_studi);
            stat.setString(4, kode_buku);
            stat.setString(5, tanggal_pinjam);
            stat.setString(6, tanggal_kembali);
            stat.setString(7, keterlambatan);
            stat.setString(8, denda);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Menyimpan data BERHASIL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            reset();
            tampil_Table_pengembalian();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menyimpan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int baris = Table_pengembalian.getSelectedRow();
        String nim = tabmode3.getValueAt(baris, 0).toString();
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data pengembalian : " + nim + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                con = connection.getConnection();
                String sql = "delete from tb_pengembalian where nim='" + nim + "'";
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Data Berhasil di hapus");
                tampil_Table_pengembalian();
                reset();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        con = connection.getConnection();
        String nim = "", nama = "", program_studi = "", kode_buku = "", tanggal_pinjam, tanggal_kembali, keterlambatan="",denda="";

        nim = text_nim.getText();
        nama = text_nama.getText();
        program_studi = text_program_studi.getText();
        kode_buku = text_kode_buku.getText();
        tanggal_pinjam = text_tanggal_pinjam.getText();
        tanggal_kembali = text_tanggal_kembali.getText();
        keterlambatan = text_keterlambatan.getText();
        denda = text_denda.getText();

        if (kode_buku == null) {
            JOptionPane.showMessageDialog(null, "Silahkan isi kode buku", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String sql = "update tb_pengembalian set nama=?, program_studi=?, kode_buku=?, tanggal_pinjam=?, tanggal_kembali=?, keterlambatan=?, denda=? where nim='" + nim + "'";
            java.sql.PreparedStatement stat = null;
            try {
                stat = con.prepareStatement(sql);
                stat.setString(1, nama);
                stat.setString(2, program_studi);
                stat.setString(3, kode_buku);
                stat.setString(4, tanggal_pinjam);
                stat.setString(5, tanggal_kembali);
                stat.setString(6, keterlambatan);
                stat.setString(7, denda);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data BERHASIL di Ubah");
                tampil_Table_pengembalian();
                reset();
            } catch (SQLException se) {
                JOptionPane.showMessageDialog(null, "Data GAGAL di Ubah");
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed
    public void pencarian_pengembalian() {
        String cari = text_search.getText();

        Object[] Baris = {"nim", "nama", "program_studi", "kode_buku", "tanggal_pinjam", "tanggal_kembali", "keterlambatan","denda"};
        tabmode3 = new DefaultTableModel(null, Baris);
        Table_pengembalian.setModel(tabmode3);

        con = connection.getConnection();

        try {
            String sql = "Select * from tb_pengembalian where "
                    + "nim like '%" + cari + "%' "
                    + "OR nama like '%" + cari + "%' "
                    + "OR program_studi like '%" + cari + "%' "
                    + "OR kode_buku like '%" + cari + "%' "
                    + "OR tanggal_pinjam like '%" + cari + "%' "
                    + "OR tanggal_kembali like '%" + cari + "%' "
                    + "OR keterlambatan like '%" + cari + "%' "
                    + "OR denda like '%" + cari + "%' "
                    + "order by nim asc";
            java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String nim = rslt.getString("nim");
                String nama = rslt.getString("nama");
                String program_studi = rslt.getString("program_studi");
                String kode_buku = rslt.getString("kode_buku");
                String tanggal_pinjam = rslt.getString("tanggal_pinjam");
                String tanggal_kembali = rslt.getString("tanggal_kembali");
                String keterlambatan = rslt.getString("keterlambatan");
                String denda = rslt.getString("denda");

                String[] dataField = {nim, nama, program_studi, kode_buku, tanggal_pinjam, tanggal_kembali, keterlambatan, denda};
                tabmode3.addRow(dataField);
            }
        } catch (Exception ex) {
        }
    }

    public void reset() {
        text_nim.setText("");
        text_nama.setText("");
        text_program_studi.setText("");
        text_kode_buku.setText("");
        text_tanggal_pinjam.setText("");
        text_tanggal_kembali.setText("");
        text_keterlambatan.setText("");
        text_denda.setText("");
    }

    private void kliktable() {
        int baris = Table_pengembalian.getSelectedRow();
        text_nim.setText((String) Table_pengembalian.getValueAt(baris, 0));
        text_nama.setText((String) Table_pengembalian.getValueAt(baris, 1));
        text_program_studi.setText((String) Table_pengembalian.getValueAt(baris, 2));
        text_kode_buku.setText((String) Table_pengembalian.getValueAt(baris, 3));
        text_tanggal_pinjam.setText((String) Table_pengembalian.getValueAt(baris, 4));
        text_tanggal_kembali.setText((String) Table_pengembalian.getValueAt(baris, 5));
        text_keterlambatan.setText((String) Table_pengembalian.getValueAt(baris, 6));
        text_denda.setText((String) Table_pengembalian.getValueAt(baris, 7));
    }
    private DefaultTableModel tabmode3;

    public void tampil_Table_pengembalian() {
        Object[] baris = {"nim", "nama", "program_studi", "kode_buku", "tanggal_pinjam", "tanggal_kembali", "keterlambatan","denda"};
        tabmode3 = new DefaultTableModel(null, baris);
        Table_pengembalian.setModel(tabmode3);
        con = connection.getConnection();
        try {
            String sql = "select * from tb_pengembalian order by nim asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rslt = stat.executeQuery(sql);
            while (rslt.next()) {
                String nim = rslt.getString("nim");
                String nama = rslt.getString("nama");
                String program_studi = rslt.getString("program_studi");
                String kode_buku = rslt.getString("kode_buku");
                String tanggal_pinjam = rslt.getString("tanggal_pinjam");
                String tanggal_kembali = rslt.getString("tanggal_kembali");
                String keterlambatan = rslt.getString("keterlambatan");
                String denda = rslt.getString("denda");
                String[] data = {nim, nama, program_studi, kode_buku, tanggal_pinjam, tanggal_kembali, keterlambatan, denda};
                tabmode3.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    private void text_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nimActionPerformed

    private void text_tanggal_pinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tanggal_pinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tanggal_pinjamActionPerformed

    private void text_tanggal_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tanggal_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tanggal_kembaliActionPerformed

    private void text_keterlambatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_keterlambatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_keterlambatanActionPerformed

    private void Table_pengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_pengembalianMouseClicked
        kliktable();
    }//GEN-LAST:event_Table_pengembalianMouseClicked

    private void text_dendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_dendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_dendaActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_program_studiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_program_studiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_program_studiActionPerformed

    private void text_kode_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_kode_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_kode_bukuActionPerformed

    private void text_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_searchMouseClicked
        text_search.setText("");
    }//GEN-LAST:event_text_searchMouseClicked
    private DefaultTableModel tabmode2;

    public void tampil_Table_peminjaman() {
        Object[] baris = {"nim", "nama", "program_studi", "kode_buku", "judul_buku", "pengarang", "tanggal_pinjam"};
        tabmode2 = new DefaultTableModel(null, baris);
        Table_peminjaman.setModel(tabmode2);
        con = connection.getConnection();
        try {
            String sql = "select * from tb_peminjaman order by nim asc";
            java.sql.Statement stat = con.createStatement();
            java.sql.ResultSet rslt = stat.executeQuery(sql);
            while (rslt.next()) {
                String nim = rslt.getString("nim");
                String nama = rslt.getString("nama");
                String program_studi = rslt.getString("program_studi");
                String kode_buku = rslt.getString("kode_buku");
                String judul_buku = rslt.getString("judul_buku");
                String pengarang = rslt.getString("pengarang");
                String tanggal_pinjam = rslt.getString("tanggal_pinjam");
                String[] data = {nim, nama, program_studi, kode_buku, judul_buku, pengarang, tanggal_pinjam};
                tabmode2.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backgroud;
    private javax.swing.JPanel Header;
    private javax.swing.JTable Table_peminjaman;
    private javax.swing.JTable Table_pengembalian;
    private javax.swing.JLabel beranda;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel btn_search;
    private javax.swing.JLabel data_buku;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel label_judul_buku;
    private javax.swing.JLabel label_kode_buku;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_pengarang;
    private javax.swing.JLabel label_program_studi;
    private javax.swing.JLabel label_tanggal_pinjam;
    private javax.swing.JLabel label_tanggal_pinjam1;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel peminjaman;
    private javax.swing.JLabel pengembaian;
    private javax.swing.JTextField text_denda;
    private javax.swing.JTextField text_keterlambatan;
    private javax.swing.JTextField text_kode_buku;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nim;
    private javax.swing.JTextField text_program_studi;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_tanggal_kembali;
    private javax.swing.JTextField text_tanggal_pinjam;
    // End of variables declaration//GEN-END:variables
}
